maybe this?

diff --git a/.github/workflows/mas_check.yml b/.github/workflows/mas_check.yml
--- a/.github/workflows/mas_check.yml
+++ b/.github/workflows/mas_check.yml
@@ -77,8 +77,8 @@ jobs:
           cd renpy
           output=$(./renpy.sh "../mas0105/" lint --error-code)
           exit_code=$?
-          echo "$output" | grep -E -v "^$|Could not find image \(monika [0-9][^[:space:]]+ corresponding to attributes on say statement\.|'monika [0-9][^[:space:]]+' is not an image\.|The image named 'monika [0-9][^[:space:]]+ was not declared\."
-          exit $exit_code
+          echo -e "${output}" | grep -E -v "^$|Could not find image \(monika [0-9][^[:space:]]+ corresponding to attributes on say statement\.|'monika [0-9][^[:space:]]+' is not an image\.|The image named 'monika [0-9][^[:space:]]+ was not declared\."
+          if [ $exit_code ]; then exit $exit_code; fi
 
       # distribute
       - name: rpy distribute
