does this fix the error codes?

diff --git a/.github/workflows/mas_check.yml b/.github/workflows/mas_check.yml
--- a/.github/workflows/mas_check.yml
+++ b/.github/workflows/mas_check.yml
@@ -75,7 +75,10 @@ jobs:
       - name: rpy lint
         run: |
           cd renpy
-          ./renpy.sh "../mas0105/" lint --error-code | grep -E -v "^$|Could not find image \(monika [0-9][^[:space:]]+ corresponding to attributes on say statement\.|'monika [0-9][^[:space:]]+' is not an image\.|The image named 'monika [0-9][^[:space:]]+ was not declared\."
+          output=$(./renpy.sh "../mas0105/" lint --error-code)
+          exit_code=$?
+          echo "$output" | grep -E -v "^$|Could not find image \(monika [0-9][^[:space:]]+ corresponding to attributes on say statement\.|'monika [0-9][^[:space:]]+' is not an image\.|The image named 'monika [0-9][^[:space:]]+ was not declared\."
+          exit $exit_code
 
       # distribute
       - name: rpy distribute
